//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//


package com.scholastic.intl.esb.integration.resource;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targetSystemOutputDetails" type="{http://resource.integration.esb.intl.scholastic.com}targetSystemOutputDetails" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "targetSystemOutputDetails"
})
@XmlRootElement(name = "addParentCustToJADEResponse")
public class AddParentCustToJADEResponse
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected List<TargetSystemOutputDetails> targetSystemOutputDetails;

    /**
     * Gets the value of the targetSystemOutputDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetSystemOutputDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetSystemOutputDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetSystemOutputDetails }
     * 
     * 
     */
    public List<TargetSystemOutputDetails> getTargetSystemOutputDetails() {
        if (targetSystemOutputDetails == null) {
            targetSystemOutputDetails = new ArrayList<TargetSystemOutputDetails>();
        }
        return this.targetSystemOutputDetails;
    }

    public boolean isSetTargetSystemOutputDetails() {
        return ((this.targetSystemOutputDetails!= null)&&(!this.targetSystemOutputDetails.isEmpty()));
    }

    public void unsetTargetSystemOutputDetails() {
        this.targetSystemOutputDetails = null;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<TargetSystemOutputDetails> theTargetSystemOutputDetails;
            theTargetSystemOutputDetails = (this.isSetTargetSystemOutputDetails()?this.getTargetSystemOutputDetails():null);
            strategy.appendField(locator, this, "targetSystemOutputDetails", buffer, theTargetSystemOutputDetails);
        }
        return buffer;
    }

}
