//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//


package com.scholastic.intl.esb.integration.resource;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for childCustData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childCustData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="companyname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subsidiary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressDataList" type="{http://resource.integration.esb.intl.scholastic.com}addressDataList"/>
 *         &lt;element name="isperson" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="shippingitem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_zonenumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountnumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="terms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creditlimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vatregnumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentitylegacy_customer_id_custom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_rewardsearner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_decile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_moe_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_rewardholder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerContacts" type="{http://resource.integration.esb.intl.scholastic.com}customerContacts" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childCustData", propOrder = {
    "parent",
    "companyname",
    "category",
    "phone",
    "subsidiary",
    "email",
    "fax",
    "addressDataList",
    "isperson",
    "shippingitem",
    "custentityZonenumber",
    "accountnumber",
    "terms",
    "currency",
    "creditlimit",
    "vatregnumber",
    "custentitylegacyCustomerIdCustom",
    "custentityRewardsearner",
    "custentityDecile",
    "custentityMoeId",
    "custentityRewardholder",
    "customerContacts"
})
public class ChildCustData
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    protected String parent;
    protected String companyname;
    protected String category;
    protected String phone;
    protected String subsidiary;
    protected String email;
    protected String fax;
    @XmlElement(required = true)
    protected AddressDataList addressDataList;
    protected Boolean isperson;
    protected String shippingitem;
    @XmlElement(name = "custentity_zonenumber")
    protected String custentityZonenumber;
    protected String accountnumber;
    protected String terms;
    protected String currency;
    protected String creditlimit;
    protected String vatregnumber;
    @XmlElement(name = "custentitylegacy_customer_id_custom")
    protected String custentitylegacyCustomerIdCustom;
    @XmlElement(name = "custentity_rewardsearner")
    protected String custentityRewardsearner;
    @XmlElement(name = "custentity_decile")
    protected String custentityDecile;
    @XmlElement(name = "custentity_moe_id")
    protected String custentityMoeId;
    @XmlElement(name = "custentity_rewardholder")
    protected String custentityRewardholder;
    protected List<CustomerContacts> customerContacts;

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParent(String value) {
        this.parent = value;
    }

    public boolean isSetParent() {
        return (this.parent!= null);
    }

    /**
     * Gets the value of the companyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * Sets the value of the companyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyname(String value) {
        this.companyname = value;
    }

    public boolean isSetCompanyname() {
        return (this.companyname!= null);
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    public boolean isSetCategory() {
        return (this.category!= null);
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    public boolean isSetPhone() {
        return (this.phone!= null);
    }

    /**
     * Gets the value of the subsidiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsidiary() {
        return subsidiary;
    }

    /**
     * Sets the value of the subsidiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsidiary(String value) {
        this.subsidiary = value;
    }

    public boolean isSetSubsidiary() {
        return (this.subsidiary!= null);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    public boolean isSetEmail() {
        return (this.email!= null);
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    public boolean isSetFax() {
        return (this.fax!= null);
    }

    /**
     * Gets the value of the addressDataList property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDataList }
     *     
     */
    public AddressDataList getAddressDataList() {
        return addressDataList;
    }

    /**
     * Sets the value of the addressDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDataList }
     *     
     */
    public void setAddressDataList(AddressDataList value) {
        this.addressDataList = value;
    }

    public boolean isSetAddressDataList() {
        return (this.addressDataList!= null);
    }

    /**
     * Gets the value of the isperson property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsperson() {
        return isperson;
    }

    /**
     * Sets the value of the isperson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsperson(Boolean value) {
        this.isperson = value;
    }

    public boolean isSetIsperson() {
        return (this.isperson!= null);
    }

    /**
     * Gets the value of the shippingitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingitem() {
        return shippingitem;
    }

    /**
     * Sets the value of the shippingitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingitem(String value) {
        this.shippingitem = value;
    }

    public boolean isSetShippingitem() {
        return (this.shippingitem!= null);
    }

    /**
     * Gets the value of the custentityZonenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityZonenumber() {
        return custentityZonenumber;
    }

    /**
     * Sets the value of the custentityZonenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityZonenumber(String value) {
        this.custentityZonenumber = value;
    }

    public boolean isSetCustentityZonenumber() {
        return (this.custentityZonenumber!= null);
    }

    /**
     * Gets the value of the accountnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountnumber() {
        return accountnumber;
    }

    /**
     * Sets the value of the accountnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountnumber(String value) {
        this.accountnumber = value;
    }

    public boolean isSetAccountnumber() {
        return (this.accountnumber!= null);
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerms(String value) {
        this.terms = value;
    }

    public boolean isSetTerms() {
        return (this.terms!= null);
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    public boolean isSetCurrency() {
        return (this.currency!= null);
    }

    /**
     * Gets the value of the creditlimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditlimit() {
        return creditlimit;
    }

    /**
     * Sets the value of the creditlimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditlimit(String value) {
        this.creditlimit = value;
    }

    public boolean isSetCreditlimit() {
        return (this.creditlimit!= null);
    }

    /**
     * Gets the value of the vatregnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatregnumber() {
        return vatregnumber;
    }

    /**
     * Sets the value of the vatregnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatregnumber(String value) {
        this.vatregnumber = value;
    }

    public boolean isSetVatregnumber() {
        return (this.vatregnumber!= null);
    }

    /**
     * Gets the value of the custentitylegacyCustomerIdCustom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentitylegacyCustomerIdCustom() {
        return custentitylegacyCustomerIdCustom;
    }

    /**
     * Sets the value of the custentitylegacyCustomerIdCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentitylegacyCustomerIdCustom(String value) {
        this.custentitylegacyCustomerIdCustom = value;
    }

    public boolean isSetCustentitylegacyCustomerIdCustom() {
        return (this.custentitylegacyCustomerIdCustom!= null);
    }

    /**
     * Gets the value of the custentityRewardsearner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityRewardsearner() {
        return custentityRewardsearner;
    }

    /**
     * Sets the value of the custentityRewardsearner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityRewardsearner(String value) {
        this.custentityRewardsearner = value;
    }

    public boolean isSetCustentityRewardsearner() {
        return (this.custentityRewardsearner!= null);
    }

    /**
     * Gets the value of the custentityDecile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityDecile() {
        return custentityDecile;
    }

    /**
     * Sets the value of the custentityDecile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityDecile(String value) {
        this.custentityDecile = value;
    }

    public boolean isSetCustentityDecile() {
        return (this.custentityDecile!= null);
    }

    /**
     * Gets the value of the custentityMoeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityMoeId() {
        return custentityMoeId;
    }

    /**
     * Sets the value of the custentityMoeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityMoeId(String value) {
        this.custentityMoeId = value;
    }

    public boolean isSetCustentityMoeId() {
        return (this.custentityMoeId!= null);
    }

    /**
     * Gets the value of the custentityRewardholder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityRewardholder() {
        return custentityRewardholder;
    }

    /**
     * Sets the value of the custentityRewardholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityRewardholder(String value) {
        this.custentityRewardholder = value;
    }

    public boolean isSetCustentityRewardholder() {
        return (this.custentityRewardholder!= null);
    }

    /**
     * Gets the value of the customerContacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerContacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerContacts }
     * 
     * 
     */
    public List<CustomerContacts> getCustomerContacts() {
        if (customerContacts == null) {
            customerContacts = new ArrayList<CustomerContacts>();
        }
        return this.customerContacts;
    }

    public boolean isSetCustomerContacts() {
        return ((this.customerContacts!= null)&&(!this.customerContacts.isEmpty()));
    }

    public void unsetCustomerContacts() {
        this.customerContacts = null;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theParent;
            theParent = this.getParent();
            strategy.appendField(locator, this, "parent", buffer, theParent);
        }
        {
            String theCompanyname;
            theCompanyname = this.getCompanyname();
            strategy.appendField(locator, this, "companyname", buffer, theCompanyname);
        }
        {
            String theCategory;
            theCategory = this.getCategory();
            strategy.appendField(locator, this, "category", buffer, theCategory);
        }
        {
            String thePhone;
            thePhone = this.getPhone();
            strategy.appendField(locator, this, "phone", buffer, thePhone);
        }
        {
            String theSubsidiary;
            theSubsidiary = this.getSubsidiary();
            strategy.appendField(locator, this, "subsidiary", buffer, theSubsidiary);
        }
        {
            String theEmail;
            theEmail = this.getEmail();
            strategy.appendField(locator, this, "email", buffer, theEmail);
        }
        {
            String theFax;
            theFax = this.getFax();
            strategy.appendField(locator, this, "fax", buffer, theFax);
        }
        {
            AddressDataList theAddressDataList;
            theAddressDataList = this.getAddressDataList();
            strategy.appendField(locator, this, "addressDataList", buffer, theAddressDataList);
        }
        {
            Boolean theIsperson;
            theIsperson = this.isIsperson();
            strategy.appendField(locator, this, "isperson", buffer, theIsperson);
        }
        {
            String theShippingitem;
            theShippingitem = this.getShippingitem();
            strategy.appendField(locator, this, "shippingitem", buffer, theShippingitem);
        }
        {
            String theCustentityZonenumber;
            theCustentityZonenumber = this.getCustentityZonenumber();
            strategy.appendField(locator, this, "custentityZonenumber", buffer, theCustentityZonenumber);
        }
        {
            String theAccountnumber;
            theAccountnumber = this.getAccountnumber();
            strategy.appendField(locator, this, "accountnumber", buffer, theAccountnumber);
        }
        {
            String theTerms;
            theTerms = this.getTerms();
            strategy.appendField(locator, this, "terms", buffer, theTerms);
        }
        {
            String theCurrency;
            theCurrency = this.getCurrency();
            strategy.appendField(locator, this, "currency", buffer, theCurrency);
        }
        {
            String theCreditlimit;
            theCreditlimit = this.getCreditlimit();
            strategy.appendField(locator, this, "creditlimit", buffer, theCreditlimit);
        }
        {
            String theVatregnumber;
            theVatregnumber = this.getVatregnumber();
            strategy.appendField(locator, this, "vatregnumber", buffer, theVatregnumber);
        }
        {
            String theCustentitylegacyCustomerIdCustom;
            theCustentitylegacyCustomerIdCustom = this.getCustentitylegacyCustomerIdCustom();
            strategy.appendField(locator, this, "custentitylegacyCustomerIdCustom", buffer, theCustentitylegacyCustomerIdCustom);
        }
        {
            String theCustentityRewardsearner;
            theCustentityRewardsearner = this.getCustentityRewardsearner();
            strategy.appendField(locator, this, "custentityRewardsearner", buffer, theCustentityRewardsearner);
        }
        {
            String theCustentityDecile;
            theCustentityDecile = this.getCustentityDecile();
            strategy.appendField(locator, this, "custentityDecile", buffer, theCustentityDecile);
        }
        {
            String theCustentityMoeId;
            theCustentityMoeId = this.getCustentityMoeId();
            strategy.appendField(locator, this, "custentityMoeId", buffer, theCustentityMoeId);
        }
        {
            String theCustentityRewardholder;
            theCustentityRewardholder = this.getCustentityRewardholder();
            strategy.appendField(locator, this, "custentityRewardholder", buffer, theCustentityRewardholder);
        }
        {
            List<CustomerContacts> theCustomerContacts;
            theCustomerContacts = (this.isSetCustomerContacts()?this.getCustomerContacts():null);
            strategy.appendField(locator, this, "customerContacts", buffer, theCustomerContacts);
        }
        return buffer;
    }

}
