//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//


package com.scholastic.intl.esb.integration.resource;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.scholastic.intl.esb.integration.resource package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.scholastic.intl.esb.integration.resource
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerContacts }
     * 
     */
    public CustomerContacts createCustomerContacts() {
        return new CustomerContacts();
    }

    /**
     * Create an instance of {@link AddParentCustToJADEResponse }
     * 
     */
    public AddParentCustToJADEResponse createAddParentCustToJADEResponse() {
        return new AddParentCustToJADEResponse();
    }

    /**
     * Create an instance of {@link TargetSystemOutputDetails }
     * 
     */
    public TargetSystemOutputDetails createTargetSystemOutputDetails() {
        return new TargetSystemOutputDetails();
    }

    /**
     * Create an instance of {@link Passport }
     * 
     */
    public Passport createPassport() {
        return new Passport();
    }

    /**
     * Create an instance of {@link InsertChildCustToNSRequest }
     * 
     */
    public InsertChildCustToNSRequest createInsertChildCustToNSRequest() {
        return new InsertChildCustToNSRequest();
    }

    /**
     * Create an instance of {@link ChildCustData }
     * 
     */
    public ChildCustData createChildCustData() {
        return new ChildCustData();
    }

    /**
     * Create an instance of {@link GetChildCustomerIdResponse }
     * 
     */
    public GetChildCustomerIdResponse createGetChildCustomerIdResponse() {
        return new GetChildCustomerIdResponse();
    }

    /**
     * Create an instance of {@link UpdParentCustToJADERequest }
     * 
     */
    public UpdParentCustToJADERequest createUpdParentCustToJADERequest() {
        return new UpdParentCustToJADERequest();
    }

    /**
     * Create an instance of {@link ParentCustData }
     * 
     */
    public ParentCustData createParentCustData() {
        return new ParentCustData();
    }

    /**
     * Create an instance of {@link GetChildCustomerIdRequest }
     * 
     */
    public GetChildCustomerIdRequest createGetChildCustomerIdRequest() {
        return new GetChildCustomerIdRequest();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link UpdateChildCustToNSResponse }
     * 
     */
    public UpdateChildCustToNSResponse createUpdateChildCustToNSResponse() {
        return new UpdateChildCustToNSResponse();
    }

    /**
     * Create an instance of {@link InsertChildCustToNSResponse }
     * 
     */
    public InsertChildCustToNSResponse createInsertChildCustToNSResponse() {
        return new InsertChildCustToNSResponse();
    }

    /**
     * Create an instance of {@link UpdateChildCustToNSRequest }
     * 
     */
    public UpdateChildCustToNSRequest createUpdateChildCustToNSRequest() {
        return new UpdateChildCustToNSRequest();
    }

    /**
     * Create an instance of {@link UpdateChildCustData }
     * 
     */
    public UpdateChildCustData createUpdateChildCustData() {
        return new UpdateChildCustData();
    }

    /**
     * Create an instance of {@link AddParentCustToJADERequest }
     * 
     */
    public AddParentCustToJADERequest createAddParentCustToJADERequest() {
        return new AddParentCustToJADERequest();
    }

    /**
     * Create an instance of {@link UpdParentCustToJADEResponse }
     * 
     */
    public UpdParentCustToJADEResponse createUpdParentCustToJADEResponse() {
        return new UpdParentCustToJADEResponse();
    }

    /**
     * Create an instance of {@link AddressDataList }
     * 
     */
    public AddressDataList createAddressDataList() {
        return new AddressDataList();
    }

    /**
     * Create an instance of {@link AddressData }
     * 
     */
    public AddressData createAddressData() {
        return new AddressData();
    }

    /**
     * Create an instance of {@link CustomerContacts.CustomerContact }
     * 
     */
    public CustomerContacts.CustomerContact createCustomerContactsCustomerContact() {
        return new CustomerContacts.CustomerContact();
    }

}
