//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://resource.integration.esb.intl.scholastic.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.scholastic.intl.esb.integration.resource;
