//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//


package com.scholastic.intl.esb.integration.resource;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for parentCustData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parentCustData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nSInternalID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salesRep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="territory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="snipmemberid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MemberStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SnippCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destinationSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subsidiary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="legacyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countrycreatedate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctrycurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctryid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctryisoCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctryname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctrystatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctrytimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ctryupdatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="utc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="createddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="updatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custcdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extaddid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rewardholder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scholasticSubCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ucreatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ustatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uupdatedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addressee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parentCustData", propOrder = {
    "addr1",
    "addr2",
    "city",
    "country",
    "email",
    "fax",
    "mobile",
    "nsInternalID",
    "name",
    "phone",
    "salesRep",
    "state",
    "territory",
    "url",
    "zip",
    "snipmemberid",
    "category",
    "memberStatus",
    "snippCountryCode",
    "destinationSystem",
    "externalid",
    "subsidiary",
    "legacyId",
    "addr3",
    "countrycreatedate",
    "ctrycurrency",
    "ctryid",
    "ctryisoCode",
    "ctryname",
    "ctrystatus",
    "ctrytimeZone",
    "ctryupdatedDate",
    "utc",
    "createddate",
    "status",
    "updatedDate",
    "custcdate",
    "extaddid",
    "id",
    "orgId",
    "orgName",
    "rewardholder",
    "scholasticSubCode",
    "custstatus",
    "userstatus",
    "ucreatedDate",
    "uid",
    "uname",
    "ustatus",
    "uupdatedDate",
    "addressee",
    "addid"
})
public class ParentCustData
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String addr1;
    @XmlElement(required = true)
    protected String addr2;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String fax;
    @XmlElement(required = true)
    protected String mobile;
    @XmlElement(name = "nSInternalID")
    protected Integer nsInternalID;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String salesRep;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String territory;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected String zip;
    @XmlElement(required = true)
    protected String snipmemberid;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(name = "MemberStatus", required = true)
    protected String memberStatus;
    @XmlElement(name = "SnippCountryCode", required = true)
    protected String snippCountryCode;
    @XmlElement(required = true)
    protected String destinationSystem;
    @XmlElement(required = true)
    protected String externalid;
    @XmlElement(required = true)
    protected String subsidiary;
    @XmlElement(required = true)
    protected String legacyId;
    @XmlElement(required = true)
    protected String addr3;
    @XmlElement(required = true)
    protected String countrycreatedate;
    @XmlElement(required = true)
    protected String ctrycurrency;
    @XmlElement(required = true)
    protected String ctryid;
    @XmlElement(required = true)
    protected String ctryisoCode;
    @XmlElement(required = true)
    protected String ctryname;
    @XmlElement(required = true)
    protected String ctrystatus;
    @XmlElement(required = true)
    protected String ctrytimeZone;
    @XmlElement(required = true)
    protected String ctryupdatedDate;
    @XmlElement(required = true)
    protected String utc;
    @XmlElement(required = true)
    protected String createddate;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String updatedDate;
    @XmlElement(required = true)
    protected String custcdate;
    @XmlElement(required = true)
    protected String extaddid;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String orgId;
    @XmlElement(required = true)
    protected String orgName;
    @XmlElement(required = true)
    protected String rewardholder;
    @XmlElement(required = true)
    protected String scholasticSubCode;
    @XmlElement(required = true)
    protected String custstatus;
    @XmlElement(required = true)
    protected String userstatus;
    @XmlElement(required = true)
    protected String ucreatedDate;
    @XmlElement(required = true)
    protected String uid;
    @XmlElement(required = true)
    protected String uname;
    @XmlElement(required = true)
    protected String ustatus;
    @XmlElement(required = true)
    protected String uupdatedDate;
    @XmlElement(required = true)
    protected String addressee;
    @XmlElement(required = true)
    protected String addid;

    /**
     * Gets the value of the addr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * Sets the value of the addr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr1(String value) {
        this.addr1 = value;
    }

    public boolean isSetAddr1() {
        return (this.addr1 != null);
    }

    /**
     * Gets the value of the addr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * Sets the value of the addr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr2(String value) {
        this.addr2 = value;
    }

    public boolean isSetAddr2() {
        return (this.addr2 != null);
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    public boolean isSetCity() {
        return (this.city!= null);
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    public boolean isSetCountry() {
        return (this.country!= null);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    public boolean isSetEmail() {
        return (this.email!= null);
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    public boolean isSetFax() {
        return (this.fax!= null);
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    public boolean isSetMobile() {
        return (this.mobile!= null);
    }

    /**
     * Gets the value of the nsInternalID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNSInternalID() {
        return nsInternalID;
    }

    /**
     * Sets the value of the nsInternalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNSInternalID(Integer value) {
        this.nsInternalID = value;
    }

    public boolean isSetNSInternalID() {
        return (this.nsInternalID!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    public boolean isSetPhone() {
        return (this.phone!= null);
    }

    /**
     * Gets the value of the salesRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesRep() {
        return salesRep;
    }

    /**
     * Sets the value of the salesRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesRep(String value) {
        this.salesRep = value;
    }

    public boolean isSetSalesRep() {
        return (this.salesRep!= null);
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    public boolean isSetState() {
        return (this.state!= null);
    }

    /**
     * Gets the value of the territory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerritory(String value) {
        this.territory = value;
    }

    public boolean isSetTerritory() {
        return (this.territory!= null);
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    public boolean isSetUrl() {
        return (this.url!= null);
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    public boolean isSetZip() {
        return (this.zip!= null);
    }

    /**
     * Gets the value of the snipmemberid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnipmemberid() {
        return snipmemberid;
    }

    /**
     * Sets the value of the snipmemberid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnipmemberid(String value) {
        this.snipmemberid = value;
    }

    public boolean isSetSnipmemberid() {
        return (this.snipmemberid!= null);
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    public boolean isSetCategory() {
        return (this.category!= null);
    }

    /**
     * Gets the value of the memberStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberStatus() {
        return memberStatus;
    }

    /**
     * Sets the value of the memberStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberStatus(String value) {
        this.memberStatus = value;
    }

    public boolean isSetMemberStatus() {
        return (this.memberStatus!= null);
    }

    /**
     * Gets the value of the snippCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnippCountryCode() {
        return snippCountryCode;
    }

    /**
     * Sets the value of the snippCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnippCountryCode(String value) {
        this.snippCountryCode = value;
    }

    public boolean isSetSnippCountryCode() {
        return (this.snippCountryCode!= null);
    }

    /**
     * Gets the value of the destinationSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationSystem() {
        return destinationSystem;
    }

    /**
     * Sets the value of the destinationSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationSystem(String value) {
        this.destinationSystem = value;
    }

    public boolean isSetDestinationSystem() {
        return (this.destinationSystem!= null);
    }

    /**
     * Gets the value of the externalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalid() {
        return externalid;
    }

    /**
     * Sets the value of the externalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalid(String value) {
        this.externalid = value;
    }

    public boolean isSetExternalid() {
        return (this.externalid!= null);
    }

    /**
     * Gets the value of the subsidiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsidiary() {
        return subsidiary;
    }

    /**
     * Sets the value of the subsidiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsidiary(String value) {
        this.subsidiary = value;
    }

    public boolean isSetSubsidiary() {
        return (this.subsidiary!= null);
    }

    /**
     * Gets the value of the legacyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacyId() {
        return legacyId;
    }

    /**
     * Sets the value of the legacyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacyId(String value) {
        this.legacyId = value;
    }

    public boolean isSetLegacyId() {
        return (this.legacyId!= null);
    }

    /**
     * Gets the value of the addr3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr3() {
        return addr3;
    }

    /**
     * Sets the value of the addr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr3(String value) {
        this.addr3 = value;
    }

    public boolean isSetAddr3() {
        return (this.addr3 != null);
    }

    /**
     * Gets the value of the countrycreatedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountrycreatedate() {
        return countrycreatedate;
    }

    /**
     * Sets the value of the countrycreatedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountrycreatedate(String value) {
        this.countrycreatedate = value;
    }

    public boolean isSetCountrycreatedate() {
        return (this.countrycreatedate!= null);
    }

    /**
     * Gets the value of the ctrycurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrycurrency() {
        return ctrycurrency;
    }

    /**
     * Sets the value of the ctrycurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrycurrency(String value) {
        this.ctrycurrency = value;
    }

    public boolean isSetCtrycurrency() {
        return (this.ctrycurrency!= null);
    }

    /**
     * Gets the value of the ctryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtryid() {
        return ctryid;
    }

    /**
     * Sets the value of the ctryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtryid(String value) {
        this.ctryid = value;
    }

    public boolean isSetCtryid() {
        return (this.ctryid!= null);
    }

    /**
     * Gets the value of the ctryisoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtryisoCode() {
        return ctryisoCode;
    }

    /**
     * Sets the value of the ctryisoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtryisoCode(String value) {
        this.ctryisoCode = value;
    }

    public boolean isSetCtryisoCode() {
        return (this.ctryisoCode!= null);
    }

    /**
     * Gets the value of the ctryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtryname() {
        return ctryname;
    }

    /**
     * Sets the value of the ctryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtryname(String value) {
        this.ctryname = value;
    }

    public boolean isSetCtryname() {
        return (this.ctryname!= null);
    }

    /**
     * Gets the value of the ctrystatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrystatus() {
        return ctrystatus;
    }

    /**
     * Sets the value of the ctrystatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrystatus(String value) {
        this.ctrystatus = value;
    }

    public boolean isSetCtrystatus() {
        return (this.ctrystatus!= null);
    }

    /**
     * Gets the value of the ctrytimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtrytimeZone() {
        return ctrytimeZone;
    }

    /**
     * Sets the value of the ctrytimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtrytimeZone(String value) {
        this.ctrytimeZone = value;
    }

    public boolean isSetCtrytimeZone() {
        return (this.ctrytimeZone!= null);
    }

    /**
     * Gets the value of the ctryupdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtryupdatedDate() {
        return ctryupdatedDate;
    }

    /**
     * Sets the value of the ctryupdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtryupdatedDate(String value) {
        this.ctryupdatedDate = value;
    }

    public boolean isSetCtryupdatedDate() {
        return (this.ctryupdatedDate!= null);
    }

    /**
     * Gets the value of the utc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtc() {
        return utc;
    }

    /**
     * Sets the value of the utc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtc(String value) {
        this.utc = value;
    }

    public boolean isSetUtc() {
        return (this.utc!= null);
    }

    /**
     * Gets the value of the createddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateddate() {
        return createddate;
    }

    /**
     * Sets the value of the createddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateddate(String value) {
        this.createddate = value;
    }

    public boolean isSetCreateddate() {
        return (this.createddate!= null);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return (this.status!= null);
    }

    /**
     * Gets the value of the updatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * Sets the value of the updatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedDate(String value) {
        this.updatedDate = value;
    }

    public boolean isSetUpdatedDate() {
        return (this.updatedDate!= null);
    }

    /**
     * Gets the value of the custcdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustcdate() {
        return custcdate;
    }

    /**
     * Sets the value of the custcdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustcdate(String value) {
        this.custcdate = value;
    }

    public boolean isSetCustcdate() {
        return (this.custcdate!= null);
    }

    /**
     * Gets the value of the extaddid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtaddid() {
        return extaddid;
    }

    /**
     * Sets the value of the extaddid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtaddid(String value) {
        this.extaddid = value;
    }

    public boolean isSetExtaddid() {
        return (this.extaddid!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the orgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgId(String value) {
        this.orgId = value;
    }

    public boolean isSetOrgId() {
        return (this.orgId!= null);
    }

    /**
     * Gets the value of the orgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

    public boolean isSetOrgName() {
        return (this.orgName!= null);
    }

    /**
     * Gets the value of the rewardholder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardholder() {
        return rewardholder;
    }

    /**
     * Sets the value of the rewardholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardholder(String value) {
        this.rewardholder = value;
    }

    public boolean isSetRewardholder() {
        return (this.rewardholder!= null);
    }

    /**
     * Gets the value of the scholasticSubCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScholasticSubCode() {
        return scholasticSubCode;
    }

    /**
     * Sets the value of the scholasticSubCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScholasticSubCode(String value) {
        this.scholasticSubCode = value;
    }

    public boolean isSetScholasticSubCode() {
        return (this.scholasticSubCode!= null);
    }

    /**
     * Gets the value of the custstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuststatus() {
        return custstatus;
    }

    /**
     * Sets the value of the custstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuststatus(String value) {
        this.custstatus = value;
    }

    public boolean isSetCuststatus() {
        return (this.custstatus!= null);
    }

    /**
     * Gets the value of the userstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstatus() {
        return userstatus;
    }

    /**
     * Sets the value of the userstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstatus(String value) {
        this.userstatus = value;
    }

    public boolean isSetUserstatus() {
        return (this.userstatus!= null);
    }

    /**
     * Gets the value of the ucreatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUcreatedDate() {
        return ucreatedDate;
    }

    /**
     * Sets the value of the ucreatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUcreatedDate(String value) {
        this.ucreatedDate = value;
    }

    public boolean isSetUcreatedDate() {
        return (this.ucreatedDate!= null);
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    public boolean isSetUid() {
        return (this.uid!= null);
    }

    /**
     * Gets the value of the uname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUname() {
        return uname;
    }

    /**
     * Sets the value of the uname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUname(String value) {
        this.uname = value;
    }

    public boolean isSetUname() {
        return (this.uname!= null);
    }

    /**
     * Gets the value of the ustatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUstatus() {
        return ustatus;
    }

    /**
     * Sets the value of the ustatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUstatus(String value) {
        this.ustatus = value;
    }

    public boolean isSetUstatus() {
        return (this.ustatus!= null);
    }

    /**
     * Gets the value of the uupdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUupdatedDate() {
        return uupdatedDate;
    }

    /**
     * Sets the value of the uupdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUupdatedDate(String value) {
        this.uupdatedDate = value;
    }

    public boolean isSetUupdatedDate() {
        return (this.uupdatedDate!= null);
    }

    /**
     * Gets the value of the addressee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressee() {
        return addressee;
    }

    /**
     * Sets the value of the addressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressee(String value) {
        this.addressee = value;
    }

    public boolean isSetAddressee() {
        return (this.addressee!= null);
    }

    /**
     * Gets the value of the addid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddid() {
        return addid;
    }

    /**
     * Sets the value of the addid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddid(String value) {
        this.addid = value;
    }

    public boolean isSetAddid() {
        return (this.addid!= null);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theAddr1;
            theAddr1 = this.getAddr1();
            strategy.appendField(locator, this, "addr1", buffer, theAddr1);
        }
        {
            String theAddr2;
            theAddr2 = this.getAddr2();
            strategy.appendField(locator, this, "addr2", buffer, theAddr2);
        }
        {
            String theCity;
            theCity = this.getCity();
            strategy.appendField(locator, this, "city", buffer, theCity);
        }
        {
            String theCountry;
            theCountry = this.getCountry();
            strategy.appendField(locator, this, "country", buffer, theCountry);
        }
        {
            String theEmail;
            theEmail = this.getEmail();
            strategy.appendField(locator, this, "email", buffer, theEmail);
        }
        {
            String theFax;
            theFax = this.getFax();
            strategy.appendField(locator, this, "fax", buffer, theFax);
        }
        {
            String theMobile;
            theMobile = this.getMobile();
            strategy.appendField(locator, this, "mobile", buffer, theMobile);
        }
        {
            Integer theNSInternalID;
            theNSInternalID = this.getNSInternalID();
            strategy.appendField(locator, this, "nsInternalID", buffer, theNSInternalID);
        }
        {
            String theName;
            theName = this.getName();
            strategy.appendField(locator, this, "name", buffer, theName);
        }
        {
            String thePhone;
            thePhone = this.getPhone();
            strategy.appendField(locator, this, "phone", buffer, thePhone);
        }
        {
            String theSalesRep;
            theSalesRep = this.getSalesRep();
            strategy.appendField(locator, this, "salesRep", buffer, theSalesRep);
        }
        {
            String theState;
            theState = this.getState();
            strategy.appendField(locator, this, "state", buffer, theState);
        }
        {
            String theTerritory;
            theTerritory = this.getTerritory();
            strategy.appendField(locator, this, "territory", buffer, theTerritory);
        }
        {
            String theUrl;
            theUrl = this.getUrl();
            strategy.appendField(locator, this, "url", buffer, theUrl);
        }
        {
            String theZip;
            theZip = this.getZip();
            strategy.appendField(locator, this, "zip", buffer, theZip);
        }
        {
            String theSnipmemberid;
            theSnipmemberid = this.getSnipmemberid();
            strategy.appendField(locator, this, "snipmemberid", buffer, theSnipmemberid);
        }
        {
            String theCategory;
            theCategory = this.getCategory();
            strategy.appendField(locator, this, "category", buffer, theCategory);
        }
        {
            String theMemberStatus;
            theMemberStatus = this.getMemberStatus();
            strategy.appendField(locator, this, "memberStatus", buffer, theMemberStatus);
        }
        {
            String theSnippCountryCode;
            theSnippCountryCode = this.getSnippCountryCode();
            strategy.appendField(locator, this, "snippCountryCode", buffer, theSnippCountryCode);
        }
        {
            String theDestinationSystem;
            theDestinationSystem = this.getDestinationSystem();
            strategy.appendField(locator, this, "destinationSystem", buffer, theDestinationSystem);
        }
        {
            String theExternalid;
            theExternalid = this.getExternalid();
            strategy.appendField(locator, this, "externalid", buffer, theExternalid);
        }
        {
            String theSubsidiary;
            theSubsidiary = this.getSubsidiary();
            strategy.appendField(locator, this, "subsidiary", buffer, theSubsidiary);
        }
        {
            String theLegacyId;
            theLegacyId = this.getLegacyId();
            strategy.appendField(locator, this, "legacyId", buffer, theLegacyId);
        }
        {
            String theAddr3;
            theAddr3 = this.getAddr3();
            strategy.appendField(locator, this, "addr3", buffer, theAddr3);
        }
        {
            String theCountrycreatedate;
            theCountrycreatedate = this.getCountrycreatedate();
            strategy.appendField(locator, this, "countrycreatedate", buffer, theCountrycreatedate);
        }
        {
            String theCtrycurrency;
            theCtrycurrency = this.getCtrycurrency();
            strategy.appendField(locator, this, "ctrycurrency", buffer, theCtrycurrency);
        }
        {
            String theCtryid;
            theCtryid = this.getCtryid();
            strategy.appendField(locator, this, "ctryid", buffer, theCtryid);
        }
        {
            String theCtryisoCode;
            theCtryisoCode = this.getCtryisoCode();
            strategy.appendField(locator, this, "ctryisoCode", buffer, theCtryisoCode);
        }
        {
            String theCtryname;
            theCtryname = this.getCtryname();
            strategy.appendField(locator, this, "ctryname", buffer, theCtryname);
        }
        {
            String theCtrystatus;
            theCtrystatus = this.getCtrystatus();
            strategy.appendField(locator, this, "ctrystatus", buffer, theCtrystatus);
        }
        {
            String theCtrytimeZone;
            theCtrytimeZone = this.getCtrytimeZone();
            strategy.appendField(locator, this, "ctrytimeZone", buffer, theCtrytimeZone);
        }
        {
            String theCtryupdatedDate;
            theCtryupdatedDate = this.getCtryupdatedDate();
            strategy.appendField(locator, this, "ctryupdatedDate", buffer, theCtryupdatedDate);
        }
        {
            String theUtc;
            theUtc = this.getUtc();
            strategy.appendField(locator, this, "utc", buffer, theUtc);
        }
        {
            String theCreateddate;
            theCreateddate = this.getCreateddate();
            strategy.appendField(locator, this, "createddate", buffer, theCreateddate);
        }
        {
            String theStatus;
            theStatus = this.getStatus();
            strategy.appendField(locator, this, "status", buffer, theStatus);
        }
        {
            String theUpdatedDate;
            theUpdatedDate = this.getUpdatedDate();
            strategy.appendField(locator, this, "updatedDate", buffer, theUpdatedDate);
        }
        {
            String theCustcdate;
            theCustcdate = this.getCustcdate();
            strategy.appendField(locator, this, "custcdate", buffer, theCustcdate);
        }
        {
            String theExtaddid;
            theExtaddid = this.getExtaddid();
            strategy.appendField(locator, this, "extaddid", buffer, theExtaddid);
        }
        {
            String theId;
            theId = this.getId();
            strategy.appendField(locator, this, "id", buffer, theId);
        }
        {
            String theOrgId;
            theOrgId = this.getOrgId();
            strategy.appendField(locator, this, "orgId", buffer, theOrgId);
        }
        {
            String theOrgName;
            theOrgName = this.getOrgName();
            strategy.appendField(locator, this, "orgName", buffer, theOrgName);
        }
        {
            String theRewardholder;
            theRewardholder = this.getRewardholder();
            strategy.appendField(locator, this, "rewardholder", buffer, theRewardholder);
        }
        {
            String theScholasticSubCode;
            theScholasticSubCode = this.getScholasticSubCode();
            strategy.appendField(locator, this, "scholasticSubCode", buffer, theScholasticSubCode);
        }
        {
            String theCuststatus;
            theCuststatus = this.getCuststatus();
            strategy.appendField(locator, this, "custstatus", buffer, theCuststatus);
        }
        {
            String theUserstatus;
            theUserstatus = this.getUserstatus();
            strategy.appendField(locator, this, "userstatus", buffer, theUserstatus);
        }
        {
            String theUcreatedDate;
            theUcreatedDate = this.getUcreatedDate();
            strategy.appendField(locator, this, "ucreatedDate", buffer, theUcreatedDate);
        }
        {
            String theUid;
            theUid = this.getUid();
            strategy.appendField(locator, this, "uid", buffer, theUid);
        }
        {
            String theUname;
            theUname = this.getUname();
            strategy.appendField(locator, this, "uname", buffer, theUname);
        }
        {
            String theUstatus;
            theUstatus = this.getUstatus();
            strategy.appendField(locator, this, "ustatus", buffer, theUstatus);
        }
        {
            String theUupdatedDate;
            theUupdatedDate = this.getUupdatedDate();
            strategy.appendField(locator, this, "uupdatedDate", buffer, theUupdatedDate);
        }
        {
            String theAddressee;
            theAddressee = this.getAddressee();
            strategy.appendField(locator, this, "addressee", buffer, theAddressee);
        }
        {
            String theAddid;
            theAddid = this.getAddid();
            strategy.appendField(locator, this, "addid", buffer, theAddid);
        }
        return buffer;
    }

}
