//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 05:35:46 AM UTC 
//


package com.scholastic.intl.esb.integration.resource;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for updateChildCustData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateChildCustData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerinternalid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inactiveflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressDataList" type="{http://resource.integration.esb.intl.scholastic.com}addressDataList" minOccurs="0"/>
 *         &lt;element name="custentity_rewardsearner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rewardsband" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subsidiary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custentity_rewardholder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateChildCustData", propOrder = {
    "customerinternalid",
    "companyname",
    "phone",
    "email",
    "fax",
    "inactiveflag",
    "addressDataList",
    "custentityRewardsearner",
    "rewardsband",
    "subsidiary",
    "custentityRewardholder"
})
public class UpdateChildCustData
    implements Serializable, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String customerinternalid;
    protected String companyname;
    protected String phone;
    protected String email;
    protected String fax;
    protected String inactiveflag;
    protected AddressDataList addressDataList;
    @XmlElement(name = "custentity_rewardsearner")
    protected String custentityRewardsearner;
    protected String rewardsband;
    protected String subsidiary;
    @XmlElement(name = "custentity_rewardholder")
    protected String custentityRewardholder;

    /**
     * Gets the value of the customerinternalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerinternalid() {
        return customerinternalid;
    }

    /**
     * Sets the value of the customerinternalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerinternalid(String value) {
        this.customerinternalid = value;
    }

    public boolean isSetCustomerinternalid() {
        return (this.customerinternalid!= null);
    }

    /**
     * Gets the value of the companyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * Sets the value of the companyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyname(String value) {
        this.companyname = value;
    }

    public boolean isSetCompanyname() {
        return (this.companyname!= null);
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    public boolean isSetPhone() {
        return (this.phone!= null);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    public boolean isSetEmail() {
        return (this.email!= null);
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    public boolean isSetFax() {
        return (this.fax!= null);
    }

    /**
     * Gets the value of the inactiveflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInactiveflag() {
        return inactiveflag;
    }

    /**
     * Sets the value of the inactiveflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInactiveflag(String value) {
        this.inactiveflag = value;
    }

    public boolean isSetInactiveflag() {
        return (this.inactiveflag!= null);
    }

    /**
     * Gets the value of the addressDataList property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDataList }
     *     
     */
    public AddressDataList getAddressDataList() {
        return addressDataList;
    }

    /**
     * Sets the value of the addressDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDataList }
     *     
     */
    public void setAddressDataList(AddressDataList value) {
        this.addressDataList = value;
    }

    public boolean isSetAddressDataList() {
        return (this.addressDataList!= null);
    }

    /**
     * Gets the value of the custentityRewardsearner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityRewardsearner() {
        return custentityRewardsearner;
    }

    /**
     * Sets the value of the custentityRewardsearner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityRewardsearner(String value) {
        this.custentityRewardsearner = value;
    }

    public boolean isSetCustentityRewardsearner() {
        return (this.custentityRewardsearner!= null);
    }

    /**
     * Gets the value of the rewardsband property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRewardsband() {
        return rewardsband;
    }

    /**
     * Sets the value of the rewardsband property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRewardsband(String value) {
        this.rewardsband = value;
    }

    public boolean isSetRewardsband() {
        return (this.rewardsband!= null);
    }

    /**
     * Gets the value of the subsidiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsidiary() {
        return subsidiary;
    }

    /**
     * Sets the value of the subsidiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsidiary(String value) {
        this.subsidiary = value;
    }

    public boolean isSetSubsidiary() {
        return (this.subsidiary!= null);
    }

    /**
     * Gets the value of the custentityRewardholder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustentityRewardholder() {
        return custentityRewardholder;
    }

    /**
     * Sets the value of the custentityRewardholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustentityRewardholder(String value) {
        this.custentityRewardholder = value;
    }

    public boolean isSetCustentityRewardholder() {
        return (this.custentityRewardholder!= null);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theCustomerinternalid;
            theCustomerinternalid = this.getCustomerinternalid();
            strategy.appendField(locator, this, "customerinternalid", buffer, theCustomerinternalid);
        }
        {
            String theCompanyname;
            theCompanyname = this.getCompanyname();
            strategy.appendField(locator, this, "companyname", buffer, theCompanyname);
        }
        {
            String thePhone;
            thePhone = this.getPhone();
            strategy.appendField(locator, this, "phone", buffer, thePhone);
        }
        {
            String theEmail;
            theEmail = this.getEmail();
            strategy.appendField(locator, this, "email", buffer, theEmail);
        }
        {
            String theFax;
            theFax = this.getFax();
            strategy.appendField(locator, this, "fax", buffer, theFax);
        }
        {
            String theInactiveflag;
            theInactiveflag = this.getInactiveflag();
            strategy.appendField(locator, this, "inactiveflag", buffer, theInactiveflag);
        }
        {
            AddressDataList theAddressDataList;
            theAddressDataList = this.getAddressDataList();
            strategy.appendField(locator, this, "addressDataList", buffer, theAddressDataList);
        }
        {
            String theCustentityRewardsearner;
            theCustentityRewardsearner = this.getCustentityRewardsearner();
            strategy.appendField(locator, this, "custentityRewardsearner", buffer, theCustentityRewardsearner);
        }
        {
            String theRewardsband;
            theRewardsband = this.getRewardsband();
            strategy.appendField(locator, this, "rewardsband", buffer, theRewardsband);
        }
        {
            String theSubsidiary;
            theSubsidiary = this.getSubsidiary();
            strategy.appendField(locator, this, "subsidiary", buffer, theSubsidiary);
        }
        {
            String theCustentityRewardholder;
            theCustentityRewardholder = this.getCustentityRewardholder();
            strategy.appendField(locator, this, "custentityRewardholder", buffer, theCustentityRewardholder);
        }
        return buffer;
    }

}
