package com.scholastic.intl.esb.integration.wsdl.palm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-06-02T10:33:16.702+05:30
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", name = "JadeNetsuiteOrgProviderSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface JadeNetsuiteOrgProviderSoap {

    @WebMethod(action = "urn:JadeWebServices/NetsuiteCustomer/updateClient")
    @RequestWrapper(localName = "updateClient", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.UpdateClientResponse")
    @WebResult(name = "updateClientResult", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
    public java.lang.String updateClient(
        @WebParam(name = "ns_client", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
        com.scholastic.intl.esb.integration.wsdl.palm.NSIClient nsClient
    );

    @WebMethod(action = "urn:JadeWebServices/NetsuiteCustomer/addParent")
    @RequestWrapper(localName = "addParent", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.AddParent")
    @ResponseWrapper(localName = "addParentResponse", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.AddParentResponse")
    @WebResult(name = "addParentResult", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
    public java.lang.String addParent(
        @WebParam(name = "organisation", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
        com.scholastic.intl.esb.integration.wsdl.palm.NSIOrganisation organisation
    );

    @WebMethod(action = "urn:JadeWebServices/NetsuiteCustomer/updateParent")
    @RequestWrapper(localName = "updateParent", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.UpdateParent")
    @ResponseWrapper(localName = "updateParentResponse", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/", className = "com.scholastic.intl.esb.integration.wsdl.palm.UpdateParentResponse")
    @WebResult(name = "updateParentResult", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
    public java.lang.String updateParent(
        @WebParam(name = "organisation", targetNamespace = "urn:JadeWebServices/NetsuiteCustomer/")
        com.scholastic.intl.esb.integration.wsdl.palm.NSIOrganisation organisation
    );
}
